if(EXISTS "/Users/yansongguo/personal/research/shamrock-wrapper/sph-code-simulation/build_tdd_test/test_gravity_soa[1]_tests.cmake")
  include("/Users/yansongguo/personal/research/shamrock-wrapper/sph-code-simulation/build_tdd_test/test_gravity_soa[1]_tests.cmake")
else()
  add_test(test_gravity_soa_NOT_BUILT test_gravity_soa_NOT_BUILT)
endif()
