#include <cmath>
#include <vector>
#include <fstream>
#include <sstream>
#include <string>
#include <random>
#include <limits>

#include "solver.hpp"
#include "simulation.hpp"
#include "particle.hpp"
#include "exception.hpp"
#include "parameters.hpp"
#include "kernel/kernel_function.hpp"
#include "periodic.hpp"

namespace sph
{

// Lane-Emden n=3/2 (gamma=5/3) hydrostatic equilibrium sphere
// Reads EXACT solution from Python-generated data file

void Solver::make_lane_emden()
{
#if DIM == 1
    THROW_ERROR("Lane-Emden test requires DIM == 2 or DIM == 3");
#else

    const int N = boost::any_cast<int>(m_sample_parameters["N"]);
#if DIM == 2
    std::cout << "Creating Lane-Emden n=3/2 hydrostatic disk (2D) with N = " << N << std::endl;
#else
    std::cout << "Creating Lane-Emden n=3/2 hydrostatic sphere (3D) with N = " << N << std::endl;
#endif
    
    auto & p = m_sim->get_particles();
    const real dx = 2.0 / N;
    const real gamma = m_param->physics.gamma;
    const real G = m_param->gravity.constant;
    
    // Physical parameters
    const real R = 1.0;          // Sphere/disk radius
    const real M_total = 1.0;    // Total mass
    
    // ========================================================================
    // READ LANE-EMDEN SOLUTION FROM FILE
    // Generated by scripts/preprocessing/generate_lane_emden.py
    // ========================================================================
    
#if DIM == 2
    std::string filename = "data/lane_emden/n1.5_2d.dat";
#else
    std::string filename = "data/lane_emden/n1.5_3d.dat";
#endif
    std::ifstream infile(filename);
    
    if(!infile.is_open()) {
        THROW_ERROR("Cannot open Lane-Emden solution file: " + filename);
    }
    
    real xi_1, dtheta_1;
    int n_points_file;
    std::vector<real> xi_array, theta_array;
    
    std::string line;
    while(std::getline(infile, line)) {
        // Skip comments and parse header
        if(line[0] == '#') {
            if(line.find("xi_1") != std::string::npos) {
                sscanf(line.c_str(), "# xi_1 = %lf", &xi_1);
            } else if(line.find("dtheta_1") != std::string::npos) {
                sscanf(line.c_str(), "# dtheta_1 = %lf", &dtheta_1);
            } else if(line.find("n_points") != std::string::npos) {
                sscanf(line.c_str(), "# n_points = %d", &n_points_file);
            }
            continue;
        }
        
        // Parse data: xi theta dtheta
        real xi, theta, dtheta;
        std::istringstream iss(line);
        if(iss >> xi >> theta >> dtheta) {
            xi_array.push_back(xi);
            theta_array.push_back(theta);
        }
    }
    infile.close();
    
    if(xi_array.empty()) {
        THROW_ERROR("Failed to read Lane-Emden solution data");
    }
    
    std::cout << "Lane-Emden: Loaded solution from " << filename << std::endl;
    std::cout << "Lane-Emden: ξ₁ = " << xi_1 << ", |dθ/dξ|_{ξ₁} = " << std::abs(dtheta_1) << std::endl;
    std::cout << "Lane-Emden: Data points: " << xi_array.size() << std::endl;
    
    // ========================================================================
    // SETUP PHYSICAL PARAMETERS
    // ========================================================================
    
    // Scaling: r = α*ξ where we want r(ξ₁) = R, so α = R/ξ₁
    const real alpha = R / xi_1;
    
#if DIM == 2
    // 2D: M = 2π α² ρ_c ξ₁ |dθ/dξ|_{ξ₁}
    const real rho_center = M_total / (2.0 * M_PI * alpha * alpha * xi_1 * std::abs(dtheta_1));
    
    // Polytropic constant for 2D: K = 2πG α² ρ_c^(1/3) / (3/2)
    const real K = 2.0 * M_PI * G * alpha * alpha * std::pow(rho_center, 1.0/3.0) / 1.5;
#else
    // 3D: M = 4π α³ ρ_c ξ₁² |dθ/dξ|_{ξ₁}
    const real rho_center = M_total / (4.0 * M_PI * alpha * alpha * alpha * xi_1 * xi_1 * std::abs(dtheta_1));
    
    // Polytropic constant: K = 4πG α² ρ_c^(1/3) / (5/2) for n=3/2
    const real K = 4.0 * M_PI * G * alpha * alpha * std::pow(rho_center, 1.0/3.0) / 2.5;
#endif
    
    std::cout << "Lane-Emden: M = " << M_total << ", R = " << R << std::endl;
    std::cout << "Lane-Emden: α = " << alpha << ", ρ_center = " << rho_center << std::endl;
    std::cout << "Lane-Emden: K = " << K << ", G = " << G << ", gamma = " << gamma << std::endl;
    
    // ========================================================================
    // CREATE EQUAL-MASS PARTICLES WITH LANE-EMDEN DENSITY PROFILE
    // Uses spherical shell distribution to avoid neighbor overflow
    // ========================================================================
    
    // Interpolation function for θ(ξ) using loaded data
    auto get_theta = [&](real xi_val) -> real {
        if(xi_val >= xi_1) return 0.0;
        if(xi_val <= 0.0) return 1.0;
        
        // Linear search for bracket
        int idx = 0;
        for(size_t i = 0; i < xi_array.size() - 1; ++i) {
            if(xi_val >= xi_array[i] && xi_val < xi_array[i+1]) {
                idx = i;
                break;
            }
        }
        
        // Linear interpolation
        const real frac = (xi_val - xi_array[idx]) / (xi_array[idx+1] - xi_array[idx]);
        return theta_array[idx] * (1.0 - frac) + theta_array[idx+1] * frac;
    };
    
    // Build cumulative mass profile M(r) for equal-mass particle placement
#if DIM == 2
    // 2D: M(r) = 2π α² ρ_c ∫₀^ξ ξ θ^n dξ where ξ = r/α
#else
    // 3D: M(r) = 4π α³ ρ_c ∫₀^ξ ξ² θ^n dξ where ξ = r/α
#endif
    std::vector<real> mass_profile(xi_array.size());
    mass_profile[0] = 0.0;
    
    for(size_t i = 1; i < xi_array.size(); ++i) {
        const real dxi = xi_array[i] - xi_array[i-1];
        const real xi_mid = 0.5 * (xi_array[i] + xi_array[i-1]);
        const real theta_mid = 0.5 * (theta_array[i] + theta_array[i-1]);
        const real rho_mid = std::pow(theta_mid, 1.5);  // ρ/ρ_c = θ^1.5
        
#if DIM == 2
        // dM = 2π α² ρ_c × ξ θ^1.5 dξ
        const real dM = 2.0 * M_PI * alpha * alpha * rho_center * xi_mid * rho_mid * dxi;
#else
        // dM = 4π α³ ρ_c × ξ² θ^1.5 dξ
        const real dM = 4.0 * M_PI * pow3(alpha) * rho_center * xi_mid * xi_mid * rho_mid * dxi;
#endif
        mass_profile[i] = mass_profile[i-1] + dM;
    }
    
    // Normalize mass profile to M_total
    const real M_computed = mass_profile.back();
    for(auto & m : mass_profile) {
        m *= M_total / M_computed;
    }
    
    std::cout << "Lane-Emden: Mass profile computed, M_check = " << M_computed << std::endl;
    
    // Determine number of particles and mass per particle
#if DIM == 2
    const int N_particles = N * N;  // N² particles for 2D
#else
    const int N_particles = N * N * N ; 
#endif
    const real particle_mass = M_total / N_particles;
    
    std::cout << "Lane-Emden: Target particle count = " << N_particles << std::endl;
    std::cout << "Lane-Emden: Particle mass = " << particle_mass << std::endl;
    
    // ========================================================================
    // GLASS-MAKING APPROACH: Pre-relaxed uniform sphere + radius mapping
    // ========================================================================
    // This method creates particles with uniform SPH density, then maps
    // their radii to match the Lane-Emden cumulative mass distribution.
    // Advantages:
    // 1. Uniform glass has correct local SPH density (~constant)
    // 2. Radius mapping preserves good neighbor distribution
    // 3. Initial SPH density much closer to target (factor 1-2×, not 10×)
    
    std::cout << "Lane-Emden: Using GLASS-MAKING initialization method" << std::endl;
    std::cout << "Lane-Emden: Step 1 - Generate uniform glass sphere..." << std::endl;
    
    // Step 1: Generate uniform glass using random positions
    std::vector<vec_t> glass_positions;
    glass_positions.reserve(N_particles);
    
    std::random_device rd;
    std::mt19937 gen(42);  // Fixed seed for reproducibility
    std::uniform_real_distribution<real> dis(-1.0, 1.0);
    
    int count_added = 0;
    while(count_added < N_particles) {
#if DIM == 2
        // 2D: Random points in circle
        vec_t pos = {dis(gen), dis(gen)};
        const real r = std::abs(pos);
        if(r <= 1.0 && r > 0.0) {
            glass_positions.push_back(pos);
            count_added++;
        }
#else
        // 3D: Random points in sphere
        vec_t pos = {dis(gen), dis(gen), dis(gen)};
        const real r = std::abs(pos);
        if(r <= 1.0 && r > 0.0) {
            glass_positions.push_back(pos);
            count_added++;
        }
#endif
    }
    
    std::cout << "Lane-Emden: Generated " << glass_positions.size() << " random particles in unit sphere" << std::endl;
    
    // Step 2: Map radii from uniform sphere to Lane-Emden profile
    // For uniform density ρ_uniform = 3M/(4πR³), cumulative mass M_uniform(r) ∝ r³
    // For Lane-Emden, cumulative mass M_LE(r) from mass_profile
    // Mapping: Find r_LE such that M_LE(r_LE) = M_uniform(r_uniform)
    
    std::cout << "Lane-Emden: Step 2 - Mapping radii to Lane-Emden profile..." << std::endl;
    
    std::vector<vec_t> mapped_positions;
    mapped_positions.reserve(N_particles);
    
    for(const auto & glass_pos : glass_positions) {
        const real r_uniform = std::abs(glass_pos);
        
        // For uniform sphere: M(r) / M_total = (r/R)³
        // We use unit sphere, so R=1, thus M(r)/M_total = r³
        const real mass_fraction = r_uniform * r_uniform * r_uniform;  // r³ for unit sphere
        const real m_target = mass_fraction * M_total;
        
        // Find r_LE in Lane-Emden profile where M(r_LE) = m_target
        real r_lane_emden = 0.0;
        for(size_t i = 1; i < mass_profile.size(); ++i) {
            if(m_target >= mass_profile[i-1] && m_target <= mass_profile[i]) {
                const real frac = (m_target - mass_profile[i-1]) / (mass_profile[i] - mass_profile[i-1]);
                const real xi_interp = xi_array[i-1] + frac * (xi_array[i] - xi_array[i-1]);
                r_lane_emden = xi_interp * alpha;
                break;
            }
        }
        
        // Handle edge cases
        if(r_lane_emden <= 0.0) {
            r_lane_emden = alpha * xi_array[0];  // Minimum radius
        }
        if(r_lane_emden > R) {
            r_lane_emden = R;  // Cap at surface
        }
        
        // Scale position vector to new radius (preserving direction)
        const real scale = r_lane_emden / r_uniform;
        vec_t pos = glass_pos * scale;
        
        mapped_positions.push_back(pos);
    }
    
    std::cout << "Lane-Emden: Mapped " << mapped_positions.size() << " particles to Lane-Emden radii" << std::endl;
    
    // ========================================================================
    // Step 3: Create SPH particles with mapped positions (POSITIONS ONLY)
    // ========================================================================
    // First pass: place particles and set mass only
    // Thermodynamic quantities will be set AFTER computing SPH density
    count_added = 0;
    for(size_t ip = 0; ip < mapped_positions.size(); ++ip) {
        vec_t pos = mapped_positions[ip];
        
        const real r = std::abs(pos);
        
        // Get Lane-Emden solution at this radius
        const real xi = r / alpha;
        const real theta = get_theta(xi);
        
        if(theta <= 0.0 || r > R) {
            continue;
        }
        
        // Density from Lane-Emden (used for initial smoothing length estimate)
        const real dens_analytic = rho_center * std::pow(theta, 1.5);
        
        if(dens_analytic <= 1e-10) {
            continue;
        }
        
        SPHParticle p_i;
        p_i.pos = pos;
        p_i.vel = 0.0;  // Initially at rest (hydrostatic equilibrium)
        p_i.mass = particle_mass;
        p_i.id = count_added;
        
        // Initial guess for smoothing length based on local analytic density
        // h ~ (N_neighbor * m / ρ / A)^(1/DIM) where A is geometric factor
        constexpr real A = DIM == 2 ? M_PI : 4.0 * M_PI / 3.0;
        const int N_neighbor = m_param->physics.neighbor_number;
        p_i.sml = std::pow(N_neighbor * particle_mass / (dens_analytic * A), 1.0 / DIM);
        
        // Store analytic density temporarily (will be overwritten by SPH density)
        p_i.dens = dens_analytic;
        
        p.emplace_back(p_i);
        count_added++;
    }
    
    std::cout << "Lane-Emden: Created " << p.size() << " particles (positions set)" << std::endl;
    
    // ========================================================================
    // Step 4: Compute SPH density using kernel sums (SELF-CONSISTENT)
    // ========================================================================
    // This ensures ρ_SPH is computed from actual particle positions
    // Then we set internal energy using ρ_SPH so P = K ρ_SPH^γ exactly
    
    std::cout << "Lane-Emden: Computing SPH density from kernel sums..." << std::endl;
    
    auto * kernel = m_sim->get_kernel().get();
    auto * periodic = m_sim->get_periodic().get();
    const int num_particles = static_cast<int>(p.size());
    
    // Compute SPH density for each particle
    real max_dens_ratio = 0.0;
    real min_dens_ratio = std::numeric_limits<real>::max();
    real sum_dens_ratio = 0.0;
    
    for(int i = 0; i < num_particles; ++i) {
        auto & p_i = p[i];
        const vec_t & pos_i = p_i.pos;
        const real h_i = p_i.sml;
        
        // Store analytic density for comparison
        const real dens_analytic = p_i.dens;
        
        // Compute SPH density: ρ_i = Σ_j m_j W(|r_i - r_j|, h_i)
        real dens_sph = 0.0;
        for(int j = 0; j < num_particles; ++j) {
            const vec_t r_ij = periodic->calc_r_ij(pos_i, p[j].pos);
            const real r = std::abs(r_ij);
            
            if(r < h_i) {
                dens_sph += p[j].mass * kernel->w(r, h_i);
            }
        }
        
        // Update particle with SPH density
        p_i.dens = dens_sph;
        
        // Compute pressure from polytropic EOS using SPH density
        // P = K * ρ_SPH^γ (SELF-CONSISTENT)
        const real pres = K * std::pow(dens_sph, gamma);
        p_i.pres = pres;
        
        // Internal energy from EOS: u = P / ((γ-1) * ρ)
        // This ensures (γ-1) * ρ_SPH * u = P = K * ρ_SPH^γ
        const real ene = pres / ((gamma - 1.0) * dens_sph);
        p_i.ene = ene;
        
        // Track density ratio for diagnostics
        const real ratio = dens_sph / dens_analytic;
        if(ratio > max_dens_ratio) max_dens_ratio = ratio;
        if(ratio < min_dens_ratio) min_dens_ratio = ratio;
        sum_dens_ratio += ratio;
    }
    
    const real avg_dens_ratio = sum_dens_ratio / num_particles;
    std::cout << "Lane-Emden: SPH density / analytic density ratio:" << std::endl;
    std::cout << "  Min: " << min_dens_ratio << ", Max: " << max_dens_ratio 
              << ", Avg: " << avg_dens_ratio << std::endl;
    
    std::cout << "Lane-Emden: Created " << p.size() << " self-consistent particles" << std::endl;
    std::cout << "Lane-Emden: Particle mass = " << particle_mass << std::endl;
#if DIM == 2
    std::cout << "Lane-Emden: Using GLASS-MAKING method with SPH-consistent EOS (2D)" << std::endl;
    std::cout << "Lane-Emden: Internal energy set from SPH density (not analytic)" << std::endl;
    std::cout << "Lane-Emden: This ensures P = K * ρ_SPH^γ exactly at t=0" << std::endl;
#else
    std::cout << "Lane-Emden: Using GLASS-MAKING method with SPH-consistent EOS" << std::endl;
    std::cout << "Lane-Emden: Internal energy set from SPH density (not analytic)" << std::endl;
    std::cout << "Lane-Emden: This ensures P = K * ρ_SPH^γ exactly at t=0" << std::endl;
#endif
    std::cout << "Lane-Emden: Relaxation will fine-tune to exact numerical equilibrium" << std::endl;
    
    // Store parameters for relaxation module
    m_sample_parameters["alpha"] = alpha;
    m_sample_parameters["rho_center"] = rho_center;
    m_sample_parameters["K"] = K;
    m_sample_parameters["R"] = R;
    m_sample_parameters["M_total"] = M_total;
    
    m_sim->set_particles(p);
    m_sim->set_particle_num(p.size());
#endif
}

}
