#include <cmath>
#include <vector>
#include <fstream>
#include <sstream>
#include <string>
#include <random>
#include <limits>

#include "solver.hpp"
#include "simulation.hpp"
#include "particle.hpp"
#include "exception.hpp"
#include "parameters.hpp"
#include "kernel/kernel_function.hpp"
#include "periodic.hpp"

namespace sph
{

// Lane-Emden n=3/2 (gamma=5/3) hydrostatic equilibrium sphere
// Reads EXACT solution from Python-generated data file

void Solver::make_lane_emden()
{
#if DIM == 1
    THROW_ERROR("Lane-Emden test requires DIM == 2 or DIM == 3");
#else

    const int N = boost::any_cast<int>(m_sample_parameters["N"]);
#if DIM == 2
    std::cout << "Creating Lane-Emden n=3/2 hydrostatic disk (2D) with N = " << N << std::endl;
#else
    std::cout << "Creating Lane-Emden n=3/2 hydrostatic sphere (3D) with N = " << N << std::endl;
#endif
    
    auto & p = m_sim->get_particles();
    const real dx = 2.0 / N;
    const real gamma = m_param->physics.gamma;
    const real G = m_param->gravity.constant;

    // Physical parameters - read from config or use defaults
    // Config can specify M_total (solar masses) and R (parsecs)
    // Default: dimensionless units (M=1, R=1)
    real R = 1.0;          // Sphere/disk radius
    real M_total = 1.0;    // Total mass

    // Check for config overrides (set in solver.cpp from JSON config)
    if (m_sample_parameters.count("M_total")) {
        M_total = boost::any_cast<real>(m_sample_parameters["M_total"]);
        std::cout << "Lane-Emden: Using M_total from config: " << M_total << " M_sun" << std::endl;
    }
    if (m_sample_parameters.count("R")) {
        R = boost::any_cast<real>(m_sample_parameters["R"]);
        std::cout << "Lane-Emden: Using R from config: " << R << " pc" << std::endl;
    }
    
    // ========================================================================
    // READ LANE-EMDEN SOLUTION FROM FILE
    // Generated by scripts/preprocessing/generate_lane_emden.py
    // ========================================================================
    
#if DIM == 2
    std::string filename = "data/lane_emden/n1.5_2d.dat";
#else
    std::string filename = "data/lane_emden/n1.5_3d.dat";
#endif
    std::ifstream infile(filename);
    
    if(!infile.is_open()) {
        THROW_ERROR("Cannot open Lane-Emden solution file: " + filename);
    }
    
    real xi_1, dtheta_1;
    int n_points_file;
    std::vector<real> xi_array, theta_array;
    
    std::string line;
    while(std::getline(infile, line)) {
        // Skip comments and parse header
        if(line[0] == '#') {
            if(line.find("xi_1") != std::string::npos) {
                sscanf(line.c_str(), "# xi_1 = %lf", &xi_1);
            } else if(line.find("dtheta_1") != std::string::npos) {
                sscanf(line.c_str(), "# dtheta_1 = %lf", &dtheta_1);
            } else if(line.find("n_points") != std::string::npos) {
                sscanf(line.c_str(), "# n_points = %d", &n_points_file);
            }
            continue;
        }
        
        // Parse data: xi theta dtheta
        real xi, theta, dtheta;
        std::istringstream iss(line);
        if(iss >> xi >> theta >> dtheta) {
            xi_array.push_back(xi);
            theta_array.push_back(theta);
        }
    }
    infile.close();
    
    if(xi_array.empty()) {
        THROW_ERROR("Failed to read Lane-Emden solution data");
    }
    
    std::cout << "Lane-Emden: Loaded solution from " << filename << std::endl;
    std::cout << "Lane-Emden: ξ₁ = " << xi_1 << ", |dθ/dξ|_{ξ₁} = " << std::abs(dtheta_1) << std::endl;
    std::cout << "Lane-Emden: Data points: " << xi_array.size() << std::endl;
    
    // ========================================================================
    // SETUP PHYSICAL PARAMETERS
    // ========================================================================
    
    // Scaling: r = α*ξ where we want r(ξ₁) = R, so α = R/ξ₁
    const real alpha = R / xi_1;
    
#if DIM == 2
    // 2D: M = 2π α² ρ_c ξ₁ |dθ/dξ|_{ξ₁}
    const real rho_center = M_total / (2.0 * M_PI * alpha * alpha * xi_1 * std::abs(dtheta_1));
    
    // Polytropic constant for 2D: K = 2πG α² ρ_c^(1/3) / (3/2)
    const real K = 2.0 * M_PI * G * alpha * alpha * std::pow(rho_center, 1.0/3.0) / 1.5;
#else
    // 3D: M = 4π α³ ρ_c ξ₁² |dθ/dξ|_{ξ₁}
    const real rho_center = M_total / (4.0 * M_PI * alpha * alpha * alpha * xi_1 * xi_1 * std::abs(dtheta_1));
    
    // Polytropic constant: K = 4πG α² ρ_c^(1/3) / (5/2) for n=3/2
    const real K = 4.0 * M_PI * G * alpha * alpha * std::pow(rho_center, 1.0/3.0) / 2.5;
#endif
    
    std::cout << "Lane-Emden: M = " << M_total << ", R = " << R << std::endl;
    std::cout << "Lane-Emden: α = " << alpha << ", ρ_center = " << rho_center << std::endl;
    std::cout << "Lane-Emden: K = " << K << ", G = " << G << ", gamma = " << gamma << std::endl;
    
    // ========================================================================
    // CREATE EQUAL-MASS PARTICLES WITH LANE-EMDEN DENSITY PROFILE
    // Uses spherical shell distribution to avoid neighbor overflow
    // ========================================================================
    
    // Interpolation function for θ(ξ) using loaded data
    auto get_theta = [&](real xi_val) -> real {
        if(xi_val >= xi_1) return 0.0;
        if(xi_val <= 0.0) return 1.0;
        
        // Linear search for bracket
        int idx = 0;
        for(size_t i = 0; i < xi_array.size() - 1; ++i) {
            if(xi_val >= xi_array[i] && xi_val < xi_array[i+1]) {
                idx = i;
                break;
            }
        }
        
        // Linear interpolation
        const real frac = (xi_val - xi_array[idx]) / (xi_array[idx+1] - xi_array[idx]);
        return theta_array[idx] * (1.0 - frac) + theta_array[idx+1] * frac;
    };
    
    // Build cumulative mass profile M(r) for equal-mass particle placement
#if DIM == 2
    // 2D: M(r) = 2π α² ρ_c ∫₀^ξ ξ θ^n dξ where ξ = r/α
#else
    // 3D: M(r) = 4π α³ ρ_c ∫₀^ξ ξ² θ^n dξ where ξ = r/α
#endif
    std::vector<real> mass_profile(xi_array.size());
    mass_profile[0] = 0.0;
    
    for(size_t i = 1; i < xi_array.size(); ++i) {
        const real dxi = xi_array[i] - xi_array[i-1];
        const real xi_mid = 0.5 * (xi_array[i] + xi_array[i-1]);
        const real theta_mid = 0.5 * (theta_array[i] + theta_array[i-1]);
        const real rho_mid = std::pow(theta_mid, 1.5);  // ρ/ρ_c = θ^1.5
        
#if DIM == 2
        // dM = 2π α² ρ_c × ξ θ^1.5 dξ
        const real dM = 2.0 * M_PI * alpha * alpha * rho_center * xi_mid * rho_mid * dxi;
#else
        // dM = 4π α³ ρ_c × ξ² θ^1.5 dξ
        const real dM = 4.0 * M_PI * pow3(alpha) * rho_center * xi_mid * xi_mid * rho_mid * dxi;
#endif
        mass_profile[i] = mass_profile[i-1] + dM;
    }
    
    // Normalize mass profile to M_total
    const real M_computed = mass_profile.back();
    for(auto & m : mass_profile) {
        m *= M_total / M_computed;
    }
    
    std::cout << "Lane-Emden: Mass profile computed, M_check = " << M_computed << std::endl;
    
    // Determine number of particles and mass per particle
#if DIM == 2
    const int N_particles = N * N;  // N² particles for 2D
#else
    const int N_particles = N * N * N ; 
#endif
    const real particle_mass = M_total / N_particles;
    
    std::cout << "Lane-Emden: Target particle count = " << N_particles << std::endl;
    std::cout << "Lane-Emden: Particle mass = " << particle_mass << std::endl;
    
    // ========================================================================
    // HEALPIX METHOD: Equal-area shells for optimal particle placement
    // ========================================================================
    // HEALPix (Hierarchical Equal Area isoLatitude Pixelization) provides
    // uniform angular distribution. Combined with equal-mass radial shells,
    // this gives excellent initial conditions requiring minimal relaxation.
    // Advantages:
    // 1. Equal-area pixels = uniform angular sampling
    // 2. Equal-mass shells = correct density distribution
    // 3. Requires only ~200-500 relaxation steps vs 10,000+ for random

    std::cout << "Lane-Emden: Using HEALPIX initialization method" << std::endl;
    std::cout << "Lane-Emden: (Requires ~10x fewer relaxation steps than random)" << std::endl;

#if DIM == 2
    // 2D: Use ring placement (simplified version of HEALPix concept)
    std::vector<vec_t> mapped_positions;
    mapped_positions.reserve(N_particles);
    std::vector<real> local_densities;
    local_densities.reserve(N_particles);

    // Number of rings ~ sqrt(N_particles)
    const int N_rings = std::max(10, static_cast<int>(std::sqrt(N_particles)));
    const real dM = M_total / N_rings;

    int total_placed = 0;
    for(int ring = 0; ring < N_rings && total_placed < N_particles; ++ring) {
        // Target mass for this ring
        const real M_target = (ring + 0.5) * dM;

        // Find radius where M_enc = M_target
        real r_ring = 0.0;
        for(size_t i = 1; i < mass_profile.size(); ++i) {
            if(M_target <= mass_profile[i]) {
                const real frac = (M_target - mass_profile[i-1]) / (mass_profile[i] - mass_profile[i-1] + 1e-20);
                r_ring = (xi_array[i-1] + frac * (xi_array[i] - xi_array[i-1])) * alpha;
                break;
            }
        }
        if(r_ring < 1e-10) r_ring = alpha * xi_array[1];
        if(r_ring > R * 0.95) continue;  // Skip shells beyond 80% of R_cloud

        // Get local density
        const real xi_ring = r_ring / alpha;
        const real theta_ring = get_theta(xi_ring);
        const real rho_local = rho_center * std::pow(std::max(theta_ring, 0.15), 1.5);  // theta_min=0.1 gives ~30:1 density contrast

        // Particles on this ring
        int N_ring = (N_particles - total_placed) / (N_rings - ring);
        N_ring = std::max(N_ring, 4);
        if(total_placed + N_ring > N_particles) N_ring = N_particles - total_placed;

        // Place particles uniformly around ring
        const real ring_rotation = ring * 2.399963229728653;  // Golden angle
        for(int i = 0; i < N_ring; ++i) {
            const real theta_angle = 2.0 * M_PI * i / N_ring + ring_rotation;
            vec_t pos = {r_ring * std::cos(theta_angle), r_ring * std::sin(theta_angle)};
            mapped_positions.push_back(pos);
            local_densities.push_back(rho_local);
        }
        total_placed += N_ring;
    }

#else
    // 3D: Full HEALPix implementation
    std::vector<vec_t> mapped_positions;
    mapped_positions.reserve(N_particles);
    std::vector<real> local_densities;
    local_densities.reserve(N_particles);

    // HEALPix pixel-to-vector function (ring scheme)
    auto healpix_pix2vec = [](int nside, int pix) -> vec_t {
        int npix = 12 * nside * nside;
        int ncap = 2 * nside * (nside - 1);  // Pixels in north polar cap

        real z, phi;

        if (pix < ncap) {
            // North polar cap
            int ph = (pix + 1) / 2;
            int ring = static_cast<int>(0.5 * (1 + std::sqrt(1 + 2*ph)));
            int iphi = (pix + 1) - 2 * ring * (ring - 1);
            z = 1.0 - (ring * ring) / (3.0 * nside * nside);
            phi = (iphi - 0.5) * M_PI / (2.0 * ring);
        } else if (pix < npix - ncap) {
            // Equatorial region
            int ip = pix - ncap;
            int ring = ip / (4 * nside) + nside;
            int iphi = ip % (4 * nside) + 1;
            int fodd = ((ring + nside) % 2 == 0) ? 1 : 0;
            z = (2 * nside - ring) / (1.5 * nside);
            phi = (iphi - 0.5 * (1 + fodd)) * M_PI / (2.0 * nside);
        } else {
            // South polar cap
            int ip = npix - pix;
            int ph = (ip + 1) / 2;
            int ring = static_cast<int>(0.5 * (1 + std::sqrt(2*ph - 1)));
            int iphi = 4 * ring + 1 - (ip - 2 * ring * (ring - 1));
            z = -1.0 + (ring * ring) / (3.0 * nside * nside);
            phi = (iphi - 0.5) * M_PI / (2.0 * ring);
        }

        real sin_theta = std::sqrt(std::max(0.0, 1.0 - z*z));
        return vec_t(sin_theta * std::cos(phi), sin_theta * std::sin(phi), z);
    };

    // Determine N_side to approximate N_particles total
    // Total pixels per shell = 12 * nside^2
    // Balance shells vs angular resolution
    int N_shells = std::max(10, static_cast<int>(std::pow(N_particles, 1.0/3.0)));
    int nside = std::max(2, static_cast<int>(std::sqrt(N_particles / (12.0 * N_shells))));
    // Round nside to power of 2 for proper HEALPix structure
    int nside_pow2 = 1;
    while (nside_pow2 * 2 <= nside) nside_pow2 *= 2;
    nside = nside_pow2;

    int npix = 12 * nside * nside;  // Pixels per shell

    // Recompute N_shells to hit N_particles
    N_shells = std::max(1, N_particles / npix);

    std::cout << "Lane-Emden: HEALPix N_side = " << nside << " (" << npix << " pixels/shell)" << std::endl;
    std::cout << "Lane-Emden: N_shells = " << N_shells << std::endl;
    std::cout << "Lane-Emden: Expected particles = " << N_shells * npix << std::endl;

    // Use cumulative mass profile to determine shell radii (equal-mass shells)
    const real dM_shell = M_total / N_shells;

    for (int s = 0; s < N_shells; ++s) {
        // Target mass for this shell
        const real M_target = (s + 0.5) * dM_shell;

        // Find radius where M_enc = M_target
        real r_shell = 0.0;
        for (size_t i = 1; i < mass_profile.size(); ++i) {
            if (M_target <= mass_profile[i]) {
                const real frac = (M_target - mass_profile[i-1]) / (mass_profile[i] - mass_profile[i-1] + 1e-20);
                r_shell = (xi_array[i-1] + frac * (xi_array[i] - xi_array[i-1])) * alpha;
                break;
            }
        }
        if (r_shell < 1e-10) r_shell = alpha * xi_array[1];

        // Truncate at 80% of R_cloud to avoid low-density boundary particles
        if (r_shell > R * 0.95) continue;

        // Get local density at this radius
        const real xi_shell = r_shell / alpha;
        const real theta_shell = get_theta(xi_shell);
        const real rho_local = rho_center * std::pow(std::max(theta_shell, 0.01), 1.5);

        // Rotate each shell by golden angle to avoid radial alignment
        const real shell_rotation = s * 2.399963229728653;  // Golden angle in radians

        // Place HEALPix pixels on this shell
        for (int p_idx = 0; p_idx < npix; ++p_idx) {
            vec_t dir = healpix_pix2vec(nside, p_idx);

            // Apply shell rotation around z-axis
            const real cos_rot = std::cos(shell_rotation);
            const real sin_rot = std::sin(shell_rotation);
            const real x_rot = dir[0] * cos_rot - dir[1] * sin_rot;
            const real y_rot = dir[0] * sin_rot + dir[1] * cos_rot;

            vec_t pos(x_rot * r_shell, y_rot * r_shell, dir[2] * r_shell);
            mapped_positions.push_back(pos);
            local_densities.push_back(rho_local);
        }
    }

    std::cout << "Lane-Emden: Created " << N_shells << " shells × " << npix << " pixels" << std::endl;
#endif

    std::cout << "Lane-Emden: Total HEALPix particles: " << mapped_positions.size() << std::endl;
    
    // ========================================================================
    // Step 3: Create SPH particles with mapped positions
    // ========================================================================
    // Use pre-computed local_densities from HEALPix shell placement
    // Recalculate particle mass based on actual number of particles created
    const int N_actual = static_cast<int>(mapped_positions.size());
    const real particle_mass_actual = M_total / N_actual;

    int count_added = 0;
    for(size_t ip = 0; ip < mapped_positions.size(); ++ip) {
        const vec_t& pos = mapped_positions[ip];
        const real dens_analytic = local_densities[ip];

        if(dens_analytic <= 1e-10) {
            continue;
        }

        SPHParticle p_i;
        p_i.pos = pos;
        p_i.vel = 0.0;  // Initially at rest (hydrostatic equilibrium)
        p_i.mass = particle_mass_actual;
        p_i.id = count_added;

        // Initial guess for smoothing length based on local analytic density
        // h ~ (N_neighbor * m / ρ / A)^(1/DIM) where A is geometric factor
        constexpr real A = DIM == 2 ? M_PI : 4.0 * M_PI / 3.0;
        const int N_neighbor = m_param->physics.neighbor_number;
        p_i.sml = std::pow(N_neighbor * particle_mass_actual / (dens_analytic * A), 1.0 / DIM);

        // Store analytic density temporarily (will be overwritten by SPH density)
        p_i.dens = dens_analytic;

        p.emplace_back(p_i);
        count_added++;
    }

    std::cout << "Lane-Emden: Created " << p.size() << " particles (HEALPix placement)" << std::endl;
    std::cout << "Lane-Emden: Actual particle mass = " << particle_mass_actual << std::endl;
    
    // ========================================================================
    // Step 4: Set thermodynamic quantities from ANALYTIC density
    // ========================================================================
    // NOTE: We skip O(N²) SPH density computation here.
    // The simulation's initial_smoothing() will recompute SPH density using
    // tree-based neighbor search, which is O(N log N).
    //
    // We set internal energy from ANALYTIC density to ensure K = const (isentropic)

    std::cout << "Lane-Emden: Setting thermodynamics from analytic density..." << std::endl;
    std::cout << "Lane-Emden: (SPH density will be computed by initial_smoothing with tree)" << std::endl;

    const int num_particles = static_cast<int>(p.size());

    for(int i = 0; i < num_particles; ++i) {
        auto & p_i = p[i];

        // p_i.dens already contains analytic density from Step 3
        const real dens_analytic = p_i.dens;

        // ====================================================================
        // Use ANALYTIC density for internal energy
        // This ensures K = P/rho^gamma is CONSTANT (isentropic) everywhere
        //
        // For true Lane-Emden equilibrium:
        //   P = K * rho_analytic^gamma (constant K everywhere)
        //   u = K * rho_analytic^(gamma-1) / (gamma - 1)
        // ====================================================================
        const real pres_analytic = K * std::pow(dens_analytic, gamma);
        const real ene_analytic = pres_analytic / ((gamma - 1.0) * dens_analytic);

        // Store internal energy based on ANALYTIC density (constant K)
        p_i.ene = ene_analytic;

        // Initial pressure from analytic density
        // Will be recomputed from SPH density after initial_smoothing()
        p_i.pres = pres_analytic;
    }

    std::cout << "Lane-Emden: Thermodynamics set for " << num_particles << " particles" << std::endl;
    
    std::cout << "Lane-Emden: Created " << p.size() << " particles with ISENTROPIC IC" << std::endl;
    std::cout << "Lane-Emden: Particle mass = " << particle_mass_actual << std::endl;
    std::cout << "Lane-Emden: Using HEALPIX method with ANALYTIC density for entropy" << std::endl;
    std::cout << "Lane-Emden: Internal energy u = K * rho_analytic^(gamma-1) / (gamma-1)" << std::endl;
    std::cout << "Lane-Emden: This ensures K = const everywhere (isentropic)" << std::endl;
    std::cout << "Lane-Emden: K = " << K << " (polytropic constant)" << std::endl;
    std::cout << "Lane-Emden: HEALPix requires ~10x fewer relaxation steps than random IC" << std::endl;
    
    // Store parameters for relaxation module
    m_sample_parameters["alpha"] = alpha;
    m_sample_parameters["rho_center"] = rho_center;
    m_sample_parameters["K"] = K;
    m_sample_parameters["R"] = R;
    m_sample_parameters["M_total"] = M_total;
    
    m_sim->set_particles(p);
    m_sim->set_particle_num(p.size());
#endif
}

}
