/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VizIndexRouteImport } from './routes/viz/index'
import { Route as ApiSimulationsRouteImport } from './routes/api/simulations'
import { Route as ApiSimulationsSimIdRouteImport } from './routes/api/simulations.$simId'
import { Route as ApiSimulationsSimIdFramesFrameIdRouteImport } from './routes/api/simulations.$simId.frames.$frameId'
import { Route as ApiSimulationsSimIdFramesFrameIdBinRouteImport } from './routes/api/simulations.$simId.frames.$frameId.bin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VizIndexRoute = VizIndexRouteImport.update({
  id: '/viz/',
  path: '/viz/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationsRoute = ApiSimulationsRouteImport.update({
  id: '/api/simulations',
  path: '/api/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationsSimIdRoute = ApiSimulationsSimIdRouteImport.update({
  id: '/$simId',
  path: '/$simId',
  getParentRoute: () => ApiSimulationsRoute,
} as any)
const ApiSimulationsSimIdFramesFrameIdRoute =
  ApiSimulationsSimIdFramesFrameIdRouteImport.update({
    id: '/frames/$frameId',
    path: '/frames/$frameId',
    getParentRoute: () => ApiSimulationsSimIdRoute,
  } as any)
const ApiSimulationsSimIdFramesFrameIdBinRoute =
  ApiSimulationsSimIdFramesFrameIdBinRouteImport.update({
    id: '/bin',
    path: '/bin',
    getParentRoute: () => ApiSimulationsSimIdFramesFrameIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/simulations': typeof ApiSimulationsRouteWithChildren
  '/viz': typeof VizIndexRoute
  '/api/simulations/$simId': typeof ApiSimulationsSimIdRouteWithChildren
  '/api/simulations/$simId/frames/$frameId': typeof ApiSimulationsSimIdFramesFrameIdRouteWithChildren
  '/api/simulations/$simId/frames/$frameId/bin': typeof ApiSimulationsSimIdFramesFrameIdBinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/simulations': typeof ApiSimulationsRouteWithChildren
  '/viz': typeof VizIndexRoute
  '/api/simulations/$simId': typeof ApiSimulationsSimIdRouteWithChildren
  '/api/simulations/$simId/frames/$frameId': typeof ApiSimulationsSimIdFramesFrameIdRouteWithChildren
  '/api/simulations/$simId/frames/$frameId/bin': typeof ApiSimulationsSimIdFramesFrameIdBinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/simulations': typeof ApiSimulationsRouteWithChildren
  '/viz/': typeof VizIndexRoute
  '/api/simulations/$simId': typeof ApiSimulationsSimIdRouteWithChildren
  '/api/simulations/$simId/frames/$frameId': typeof ApiSimulationsSimIdFramesFrameIdRouteWithChildren
  '/api/simulations/$simId/frames/$frameId/bin': typeof ApiSimulationsSimIdFramesFrameIdBinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/simulations'
    | '/viz'
    | '/api/simulations/$simId'
    | '/api/simulations/$simId/frames/$frameId'
    | '/api/simulations/$simId/frames/$frameId/bin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/simulations'
    | '/viz'
    | '/api/simulations/$simId'
    | '/api/simulations/$simId/frames/$frameId'
    | '/api/simulations/$simId/frames/$frameId/bin'
  id:
    | '__root__'
    | '/'
    | '/api/simulations'
    | '/viz/'
    | '/api/simulations/$simId'
    | '/api/simulations/$simId/frames/$frameId'
    | '/api/simulations/$simId/frames/$frameId/bin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSimulationsRoute: typeof ApiSimulationsRouteWithChildren
  VizIndexRoute: typeof VizIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viz/': {
      id: '/viz/'
      path: '/viz'
      fullPath: '/viz'
      preLoaderRoute: typeof VizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulations': {
      id: '/api/simulations'
      path: '/api/simulations'
      fullPath: '/api/simulations'
      preLoaderRoute: typeof ApiSimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulations/$simId': {
      id: '/api/simulations/$simId'
      path: '/$simId'
      fullPath: '/api/simulations/$simId'
      preLoaderRoute: typeof ApiSimulationsSimIdRouteImport
      parentRoute: typeof ApiSimulationsRoute
    }
    '/api/simulations/$simId/frames/$frameId': {
      id: '/api/simulations/$simId/frames/$frameId'
      path: '/frames/$frameId'
      fullPath: '/api/simulations/$simId/frames/$frameId'
      preLoaderRoute: typeof ApiSimulationsSimIdFramesFrameIdRouteImport
      parentRoute: typeof ApiSimulationsSimIdRoute
    }
    '/api/simulations/$simId/frames/$frameId/bin': {
      id: '/api/simulations/$simId/frames/$frameId/bin'
      path: '/bin'
      fullPath: '/api/simulations/$simId/frames/$frameId/bin'
      preLoaderRoute: typeof ApiSimulationsSimIdFramesFrameIdBinRouteImport
      parentRoute: typeof ApiSimulationsSimIdFramesFrameIdRoute
    }
  }
}

interface ApiSimulationsSimIdFramesFrameIdRouteChildren {
  ApiSimulationsSimIdFramesFrameIdBinRoute: typeof ApiSimulationsSimIdFramesFrameIdBinRoute
}

const ApiSimulationsSimIdFramesFrameIdRouteChildren: ApiSimulationsSimIdFramesFrameIdRouteChildren =
  {
    ApiSimulationsSimIdFramesFrameIdBinRoute:
      ApiSimulationsSimIdFramesFrameIdBinRoute,
  }

const ApiSimulationsSimIdFramesFrameIdRouteWithChildren =
  ApiSimulationsSimIdFramesFrameIdRoute._addFileChildren(
    ApiSimulationsSimIdFramesFrameIdRouteChildren,
  )

interface ApiSimulationsSimIdRouteChildren {
  ApiSimulationsSimIdFramesFrameIdRoute: typeof ApiSimulationsSimIdFramesFrameIdRouteWithChildren
}

const ApiSimulationsSimIdRouteChildren: ApiSimulationsSimIdRouteChildren = {
  ApiSimulationsSimIdFramesFrameIdRoute:
    ApiSimulationsSimIdFramesFrameIdRouteWithChildren,
}

const ApiSimulationsSimIdRouteWithChildren =
  ApiSimulationsSimIdRoute._addFileChildren(ApiSimulationsSimIdRouteChildren)

interface ApiSimulationsRouteChildren {
  ApiSimulationsSimIdRoute: typeof ApiSimulationsSimIdRouteWithChildren
}

const ApiSimulationsRouteChildren: ApiSimulationsRouteChildren = {
  ApiSimulationsSimIdRoute: ApiSimulationsSimIdRouteWithChildren,
}

const ApiSimulationsRouteWithChildren = ApiSimulationsRoute._addFileChildren(
  ApiSimulationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSimulationsRoute: ApiSimulationsRouteWithChildren,
  VizIndexRoute: VizIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
