if(EXISTS "/Users/yansongguo/personal/research/shamrock-wrapper/sph-code-simulation/build_test_3d/test_neighbor_search[1]_tests.cmake")
  include("/Users/yansongguo/personal/research/shamrock-wrapper/sph-code-simulation/build_test_3d/test_neighbor_search[1]_tests.cmake")
else()
  add_test(test_neighbor_search_NOT_BUILT test_neighbor_search_NOT_BUILT)
endif()
