if(EXISTS "/Users/kunishigehana/sph-code-simulation/build_test/test_neighbor_search[1]_tests.cmake")
  include("/Users/kunishigehana/sph-code-simulation/build_test/test_neighbor_search[1]_tests.cmake")
else()
  add_test(test_neighbor_search_NOT_BUILT test_neighbor_search_NOT_BUILT)
endif()
