if(EXISTS "/Users/kunishigehana/sph-code-simulation/build_test/test_morton[1]_tests.cmake")
  include("/Users/kunishigehana/sph-code-simulation/build_test/test_morton[1]_tests.cmake")
else()
  add_test(test_morton_NOT_BUILT test_morton_NOT_BUILT)
endif()
